:PREAMBLE:
#+title: Epkgs: Orphanage
#+setupfile: .orgconfig
#+name: setup
#+begin_src emacs-lisp :results silent
  (require 'emir)

  (defconst emir--orphans-cache
    (cl-delete-if (lambda (it)
                    (member (cdr (assq 'name it))
                            '(".github" "p")))
                  (cl-sort (ghub-get "/orgs/emacsorphanage/repos" nil
                                     :unpaginate t
                                     :auth 'emir)
                           #'string< :key (lambda (it) (cdr (assq 'name it))))))

  (defun emir--list-orphans (&rest only)
    (epkg-with-org-header ("Package" "E" "M")
      (--keep
       (let* ((name (cdr (assq 'name it)))
              (name (if (equal name "image-plus") "image+" name))
              (pkg  (epkg name))
              (type (and pkg (closql--abbrev-class (eieio-object-class pkg))))
              (rcp  (melpa-get name))
              (reason (emir--config name :orphanage)))
         (and (or (not only)
                  (member reason only))
              (list name
                    (if pkg (if (eq type 'orphaned) "✔" type) "")
                    (if rcp
                        (if (string-prefix-p "emacsorphanage/" (oref rcp repo))
                            "✔"
                          (closql--abbrev-class (eieio-object-class rcp)))
                      ""))))
       emir--orphans-cache)))
#+end_src
[[https://emacsmirror.net/stats][up]]
:END:
* Upstream has disappeared but there are dependents

The upstream repository or file download for these packages has
disappeared.

Or at least it wasn't available for a long time; in some cases the
upstream might be available again.  I do not check to make sure this
is not the case.  If you find such a package, then please let me know.

Of course there are many more packages whose upstream has disappeared,
then those listed here, many of which can be found on the Emacsattic.

Those unmaintained packages that made it into the orphanage instead of
just the attic, did so because other mirrored packages depend on them,
and/or because they are available from Melpa (I mirror all packages
that are available from there).

#+name: disappeared
#+begin_src emacs-lisp
  (emir--list-orphans "upstream disappeared")
#+end_src
#+results: disappeared
| Package (10) | E | M |
|--------------+---+---|
| dedicated    | ✔ | ✔ |
| ecasound     | ✔ |   |
| image+       | ✔ | ✔ |
| keydef       | ✔ | ✔ |
| miniedit     | ✔ | ✔ |
| osd          | ✔ |   |
| pager        | ✔ | ✔ |
| smarty-mode  | ✔ | ✔ |
| tail         | ✔ |   |
| vm           | ✔ |   |

* Upstream is unresponsive but there are issues

The upstream repositories for these packages still existed (or at
least they still existed when the packages were added here), but the
packages have issues that have to be fixed and the maintainers did not
respond when I contacted them.  I have patched these packages here in
the orphanage to fix these issues.

- Multiple packages bundle ~hyperspec~ but none of them is the
  authoritive upstream.  Attempts to get the various non-upstreams
  talking have failed so far.

#+name: unresponsive
#+begin_src emacs-lisp
  (emir--list-orphans "upstream unresponsive" "multiple non-upstreams")
#+end_src
#+results: unresponsive
| Package (7)    | E | M |
|----------------+---+---|
| edb            | ✔ |   |
| elisp-depend   | ✔ | ✔ |
| hyperspec      | ✔ |   |
| oberon         | ✔ | ✔ |
| read-char-spec | ✔ |   |
| setnu          | ✔ |   |
| yafolding      | ✔ | ✔ |

* Wiki packages needed by non-wiki packages

These packages are being distributed on the Emacswiki and other
packages that are not distributed on the Emacswiki depend on them.

Anyone can edit packages on the Emacswiki, which is a big security
risk, so we "mirror" a frozen copy from the orphanage instead of
the world-writable copy from the wiki.

Melpa also uses the frozen copies, see issue [[https://github.com/melpa/melpa/issues/2342][#2342]].

#+name: required-by-nonwiki
#+begin_src emacs-lisp
  (emir--list-orphans "wiki needed by non-wiki")
#+end_src
#+results: required-by-nonwiki
| Package (27)       | E | M |
|--------------------+---+---|
| cygwin-mount       | ✔ |   |
| dirtree            | ✔ | ✔ |
| el-expectations    | ✔ |   |
| ert-expectations   | ✔ | ✔ |
| extract-text       | ✔ |   |
| findr              | ✔ | ✔ |
| highline           | ✔ |   |
| http-post-simple   | ✔ | ✔ |
| imdb               | ✔ |   |
| key-chord          | ✔ | ✔ |
| keyword-arg-macros | ✔ |   |
| later-do           | ✔ |   |
| levenshtein        | ✔ | ✔ |
| oddmuse            | ✔ |   |
| org-json           | ✔ |   |
| policy-switch      | ✔ |   |
| run-assoc          | ✔ |   |
| screenshot         | ✔ |   |
| shell-history      | ✔ | ✔ |
| showtip            | ✔ | ✔ |
| sr-speedbar        | ✔ | ✔ |
| transpose-frame    | ✔ | ✔ |
| tree-mode          | ✔ | ✔ |
| unit-test          | ✔ |   |
| w32-browser        | ✔ | ✔ |
| windata            | ✔ | ✔ |
| yaoddmuse          | ✔ |   |

* Imported from tarball
#+name: tarball
#+begin_src emacs-lisp
  (emir--list-orphans "manual tarball import")
#+end_src
#+results: tarball
| Package (3)  | E | M |
|--------------+---+---|
| picolisp     | ✔ |   |
| session      | ✔ | ✔ |
| sml-modeline | ✔ | ✔ |

* Dropped of by maintainer
#+name: dropped
#+begin_src emacs-lisp
  (emir--list-orphans "dropped by maintainer")
#+end_src
#+results: dropped
| Package (82)         | E | M |
|----------------------+---+---|
| 4clojure             | ✔ | ✔ |
| ac-alchemist         | ✔ | ✔ |
| ac-capf              | ✔ | ✔ |
| ac-emoji             | ✔ | ✔ |
| ac-etags             | ✔ | ✔ |
| ac-ispell            | ✔ | ✔ |
| ac-racer             | ✔ | ✔ |
| ansible-doc          | ✔ | ✔ |
| anzu                 | ✔ | ✔ |
| applescript-mode     | ✔ | ✔ |
| codic                | ✔ | ✔ |
| company-jedi         | ✔ | ✔ |
| cpp-auto-include     | ✔ | ✔ |
| dired-k              | ✔ | ✔ |
| direx                | ✔ | ✔ |
| docean               | ✔ | ✔ |
| easy-highlight       | ✔ |   |
| emamux               | ✔ | ✔ |
| emamux-ruby-test     | ✔ | ✔ |
| evil-anzu            | ✔ | ✔ |
| evil-textobj-line    | ✔ | ✔ |
| fancy-battery        | ✔ | ✔ |
| fontawesome          | ✔ | ✔ |
| gh-md                | ✔ | ✔ |
| git-gutter           | ✔ | ✔ |
| git-gutter-fringe    | ✔ | ✔ |
| git-messenger        | ✔ | ✔ |
| go-add-tags          | ✔ | ✔ |
| go-direx             | ✔ | ✔ |
| go-eldoc             | ✔ | ✔ |
| go-impl              | ✔ | ✔ |
| god-mode             | ✔ | ✔ |
| gom-mode             | ✔ | ✔ |
| haxe-mode            | ✔ | ✔ |
| helm-ack             | ✔ | ✔ |
| helm-ag              | ✔ | ✔ |
| helm-css-scss        | ✔ | ✔ |
| helm-github-issues   | ✔ |   |
| helm-gtags           | ✔ | ✔ |
| helm-haskell-import  | ✔ |   |
| helm-ispell          | ✔ | ✔ |
| helm-open-github     | ✔ | ✔ |
| helm-package         | ✔ |   |
| helm-perldoc         | ✔ | ✔ |
| helm-pydoc           | ✔ | ✔ |
| helm-robe            | ✔ | ✔ |
| helm-swoop           | ✔ | ✔ |
| helm-themes          | ✔ | ✔ |
| import-popwin        | ✔ | ✔ |
| jedi-eldoc           | ✔ |   |
| konoha-mode          | ✔ |   |
| literate-coffee-mode | ✔ | ✔ |
| ltsv                 | ✔ |   |
| magit-gerrit         | ✔ | ✔ |
| magit-p4             | ✔ | ✔ |
| magit-svn            | ✔ | ✔ |
| manage-minor-mode    | ✔ | ✔ |
| mongo                | ✔ | ✔ |
| octicons             | ✔ | ✔ |
| opam                 | ✔ | ✔ |
| org-page             | ✔ | ✔ |
| osx-trash            | ✔ | ✔ |
| ov                   | ✔ | ✔ |
| perl-utils           | ✔ |   |
| pkg-info             | ✔ | ✔ |
| popup-complete       | ✔ | ✔ |
| popwin               | ✔ | ✔ |
| pyimpsort            | ✔ | ✔ |
| quickrun             | ✔ | ✔ |
| reverse-theme        | ✔ | ✔ |
| smeargle             | ✔ | ✔ |
| sound-wav            | ✔ | ✔ |
| sourcemap            | ✔ | ✔ |
| splitjoin            | ✔ | ✔ |
| swoop                | ✔ | ✔ |
| terraform-mode       | ✔ | ✔ |
| test-more            | ✔ |   |
| thingopt             | ✔ | ✔ |
| tora-mode            | ✔ |   |
| undohist             | ✔ | ✔ |
| yascroll             | ✔ | ✔ |
| zoom-window          | ✔ | ✔ |

* Revived using the orphanage

The upstream has become unresponsive and a volunteer now maintains a
fork under the umbrella of the orphanage.  I believe there are a few
more packages in this category than listed below, but for a long time
we did not track this as a separate reason for a package to be in the
orphanage.

#+name: revived
#+begin_src emacs-lisp
  (emir--list-orphans "revived using fork")
#+end_src
#+results: revived
| Package (1) | E | M |
|-------------+---+---|
| ox-pandoc   | ✔ | ✔ |

* Other
#+name: rip
#+begin_src emacs-lisp
  (emir--list-orphans "maintainer is dead" "last subversion")
#+end_src
#+results: rip
| Package (2)    | E | M |
|----------------+---+---|
| dic-lookup-w3m | ✔ | ✔ |
| org-grep       | ✔ | ✔ |

* New
#+name: new
#+begin_src emacs-lisp
  (emir--list-orphans nil)
#+end_src
#+results: new
| Package (1)     | E      | M      |
|-----------------+--------+--------|
| farmhouse-theme | github | github |

