:PREAMBLE:
#+TITLE: Epkgs: Orphanage
#+SETUPFILE: .orgconfig
#+NAME: setup
#+BEGIN_SRC emacs-lisp :results silent
  (require 'emir)

  (defconst emir--orphans-cache
    (cl-delete-if (lambda (it)
                    (member (cdr (assq 'name it))
                            '(".github" "p")))
                  (cl-sort (ghub-get "/orgs/emacsorphanage/repos" nil
                                     :unpaginate t
                                     :auth 'emir)
                           #'string< :key (lambda (it) (cdr (assq 'name it))))))

  (defun emir--list-orphans (&rest only)
    (epkg-with-org-header ("Package" "E" "M")
      (--keep
       (let* ((name (cdr (assq 'name it)))
              (pkg  (epkg name))
              (rcp  (melpa-get name))
              (reason (cadr (assoc name emir--orphanage-reason))))
         (and (or (not only)
                  (member reason only))
              (list name
                    (if pkg "✔" "")
                    (if rcp
                        (if (string-prefix-p "emacsorphanage/" (oref rcp repo))
                            "✔"
                          (closql--abbrev-class (eieio-object-class rcp)))
                      ""))))
       emir--orphans-cache)))
#+END_SRC
[[https://emacsmirror.net/stats][up]]
:END:
* Upstream has disappeared but there are dependents

The upstream repository or file download for these packages has
disappeared.

Or at least it wasn't available for a long time; in some cases the
upstream might be available again.  I do not check to make sure this
is not the case.  If you find such a package, then please let me know.

Of course there are many more packages whose upstream has disappeared,
then those listed here, many of which can be found on the Emacsattic.

Those unmaintained packages that made it into the orphanage instead of
just the attic, did so because other mirrored packages depend on them,
and/or because they are available from Melpa (I mirror all packages
that are available from there).

#+NAME: disappeared
#+BEGIN_SRC emacs-lisp
  (emir--list-orphans "upstream disappeared")
#+END_SRC
#+RESULTS: disappeared
| Package (8) | E | M |
|-------------+---+---|
| dedicated   | ✔ | ✔ |
| ecasound    | ✔ |   |
| keydef      | ✔ | ✔ |
| miniedit    | ✔ | ✔ |
| osd         | ✔ |   |
| pager       | ✔ | ✔ |
| smarty-mode | ✔ | ✔ |
| tail        | ✔ |   |

* Upstream is unresponsive but there are issues

The upstream repositories for these packages still existed (or at
least they still existed when the packages were added here), but the
packages have issues that have to be fixed and the maintainers did not
respond when I contacted them.  I have patched these packages here in
the orphanage to fix these issues.

- Multiple packages bundle ~hyperspec~ but none of them is the
  authoritive upstream.  Attempts to get the various non-upstreams
  talking have failed so far.

#+NAME: unresponsive
#+BEGIN_SRC emacs-lisp
  (emir--list-orphans "upstream unresponsive" "multiple non-upstreams")
#+END_SRC
#+RESULTS: unresponsive
| Package (7)    | E | M |
|----------------+---+---|
| edb            | ✔ |   |
| elisp-depend   | ✔ | ✔ |
| hyperspec      | ✔ |   |
| oberon         | ✔ | ✔ |
| read-char-spec | ✔ |   |
| setnu          | ✔ |   |
| yafolding      | ✔ | ✔ |

* Wiki packages needed by non-wiki packages

These packages are being distributed on the Emacswiki and other
packages that are not distributed on the Emacswiki depend on them.

Anyone can edit packages on the Emacswiki, which is a big security
risk, so we "mirror" a frozen copy from the orphanage instead of
the world-writable copy from the wiki.

Melpa also uses the frozen copies, see issue [[https://github.com/melpa/melpa/issues/2342][#2342]].

#+NAME: required-by-nonwiki
#+BEGIN_SRC emacs-lisp
  (emir--list-orphans "wiki needed by non-wiki" "wiki multiple files")
#+END_SRC
#+RESULTS: required-by-nonwiki
| Package (30)       | E | M |
|--------------------+---+---|
| cygwin-mount       | ✔ |   |
| dirtree            | ✔ | ✔ |
| el-expectations    | ✔ |   |
| ert-expectations   | ✔ | ✔ |
| extract-text       | ✔ |   |
| findr              | ✔ | ✔ |
| highline           | ✔ |   |
| http-post-simple   | ✔ | ✔ |
| imdb               | ✔ |   |
| key-chord          | ✔ | ✔ |
| keyword-arg-macros | ✔ |   |
| later-do           | ✔ |   |
| levenshtein        | ✔ | ✔ |
| linkd              | ✔ |   |
| oddmuse            | ✔ |   |
| org-json           | ✔ |   |
| policy-switch      | ✔ |   |
| run-assoc          | ✔ |   |
| screenshot         | ✔ |   |
| shell-command      | ✔ |   |
| shell-history      | ✔ | ✔ |
| showtip            | ✔ | ✔ |
| sr-speedbar        | ✔ | ✔ |
| transpose-frame    | ✔ | ✔ |
| tree-mode          | ✔ | ✔ |
| unit-test          | ✔ |   |
| vline              | ✔ |   |
| w32-browser        | ✔ | ✔ |
| windata            | ✔ | ✔ |
| yaoddmuse          | ✔ |   |

* Imported from non-git/hg repository

The tools used to maintain the Emacsmirror do not support ~bzr~, ~cvs~,
~darcs~, or ~fossil~.  So I manually import the upstream repositories into
a ~git~ repository on the orphanage and then import the resulting ~git~
repositories as if that were the actual upstream.

I do not regularly update these repositories.  If you find that they
are outdated, then please let me know.  However many of these package
repositories have not seen a commit in a decade.

#+NAME: non-git-hg
#+BEGIN_SRC emacs-lisp
  (emir--list-orphans "semi-automatic import")
#+END_SRC
#+RESULTS: non-git-hg
| Package (4)    | E | M |
|----------------+---+---|
| confluence     | ✔ | ✔ |
| dic-lookup-w3m | ✔ | ✔ |
| nxhtml         | ✔ |   |
| vm             | ✔ |   |

* Imported from tarball
#+NAME: tarball
#+BEGIN_SRC emacs-lisp
  (emir--list-orphans "manual tarball import")
#+END_SRC
#+RESULTS: tarball
| Package (3)  | E | M |
|--------------+---+---|
| picolisp     | ✔ |   |
| session      | ✔ | ✔ |
| sml-modeline | ✔ | ✔ |

* Dropped of by maintainer
#+NAME: dropped
#+BEGIN_SRC emacs-lisp
  (emir--list-orphans "dropped by maintainer")
#+END_SRC
#+RESULTS: dropped
| Package (84)         | E | M |
|----------------------+---+---|
| 4clojure             | ✔ | ✔ |
| ac-alchemist         | ✔ | ✔ |
| ac-capf              | ✔ | ✔ |
| ac-emoji             | ✔ | ✔ |
| ac-etags             | ✔ | ✔ |
| ac-ispell            | ✔ | ✔ |
| ac-racer             | ✔ | ✔ |
| ansible-doc          | ✔ | ✔ |
| anzu                 | ✔ | ✔ |
| applescript-mode     | ✔ | ✔ |
| codic                | ✔ | ✔ |
| company-jedi         | ✔ | ✔ |
| cpp-auto-include     | ✔ | ✔ |
| dired-k              | ✔ | ✔ |
| direx                | ✔ | ✔ |
| docean               | ✔ | ✔ |
| easy-highlight       | ✔ |   |
| emamux               | ✔ | ✔ |
| emamux-ruby-test     | ✔ | ✔ |
| evil-anzu            | ✔ | ✔ |
| evil-textobj-line    | ✔ | ✔ |
| fancy-battery        | ✔ | ✔ |
| fontawesome          | ✔ | ✔ |
| gh-md                | ✔ | ✔ |
| git-gutter           | ✔ | ✔ |
| git-gutter-fringe    | ✔ | ✔ |
| git-messenger        | ✔ | ✔ |
| gnuplot              | ✔ | ✔ |
| go-add-tags          | ✔ | ✔ |
| go-direx             | ✔ | ✔ |
| go-eldoc             | ✔ | ✔ |
| go-impl              | ✔ | ✔ |
| god-mode             | ✔ | ✔ |
| gom-mode             | ✔ | ✔ |
| haxe-mode            | ✔ | ✔ |
| helm-ack             | ✔ | ✔ |
| helm-ag              | ✔ | ✔ |
| helm-css-scss        | ✔ | ✔ |
| helm-github-issues   | ✔ |   |
| helm-gtags           | ✔ | ✔ |
| helm-haskell-import  | ✔ |   |
| helm-ispell          | ✔ | ✔ |
| helm-open-github     | ✔ | ✔ |
| helm-package         | ✔ |   |
| helm-perldoc         | ✔ | ✔ |
| helm-pydoc           | ✔ | ✔ |
| helm-robe            | ✔ | ✔ |
| helm-swoop           | ✔ | ✔ |
| helm-themes          | ✔ | ✔ |
| import-popwin        | ✔ | ✔ |
| jedi-eldoc           | ✔ |   |
| konoha-mode          | ✔ |   |
| literate-coffee-mode | ✔ | ✔ |
| ltsv                 | ✔ |   |
| magit-gerrit         | ✔ | ✔ |
| magit-p4             | ✔ | ✔ |
| magit-stgit          | ✔ | ✔ |
| magit-svn            | ✔ | ✔ |
| manage-minor-mode    | ✔ | ✔ |
| mongo                | ✔ | ✔ |
| octicons             | ✔ | ✔ |
| opam                 | ✔ | ✔ |
| org-page             | ✔ | ✔ |
| osx-trash            | ✔ | ✔ |
| ov                   | ✔ | ✔ |
| perl-utils           | ✔ |   |
| pkg-info             | ✔ | ✔ |
| popup-complete       | ✔ | ✔ |
| popwin               | ✔ | ✔ |
| pyimpsort            | ✔ | ✔ |
| quickrun             | ✔ | ✔ |
| reverse-theme        | ✔ | ✔ |
| smeargle             | ✔ | ✔ |
| sound-wav            | ✔ | ✔ |
| sourcemap            | ✔ | ✔ |
| splitjoin            | ✔ | ✔ |
| swoop                | ✔ | ✔ |
| terraform-mode       | ✔ | ✔ |
| test-more            | ✔ |   |
| thingopt             | ✔ | ✔ |
| tora-mode            | ✔ |   |
| undohist             | ✔ | ✔ |
| yascroll             | ✔ | ✔ |
| zoom-window          | ✔ | ✔ |

* The maintainer is dead

Sadly there is one package where "orphan" has a more literal meaning
than what I had in mind when I created the Emacs Orphanage.  RIP
François.

#+NAME: rip
#+BEGIN_SRC emacs-lisp
  (emir--list-orphans "maintainer is dead")
#+END_SRC
#+RESULTS: rip
| Package (1) | E | M |
|-------------+---+---|
| org-grep    | ✔ | ✔ |

* New
#+NAME: new
#+BEGIN_SRC emacs-lisp
  (emir--list-orphans nil)
#+END_SRC
#+RESULTS: new

