#+SETUPFILE: .orgconfig
#+NAME: setup
#+BEGIN_SRC emacs-lisp :results silent
  (require 'epkg)

  (defun emir--format-license-table (table)
    (setcar (assq nil table) "(unknown)")
    (let ((total (apply '+ (mapcar 'cadr table)))
          (gnu   (apply '+ (mapcar (pcase-lambda (`(,license ,count))
                                     (if (string-match-p "GPL" license) count 0))
                                   table))))
        (cl-flet ((percent (n) (round (* (/ n total 1.0) 100))))
          `(("License" "Count" "Percent")
            hline ,@(mapcar (pcase-lambda (`(,license ,count))
                              (list license count (percent count)))
                            table)
            hline ("total GNU" ,gnu ,(percent gnu))
            hline ("total" ,total 100)))))
#+END_SRC
[[https://emacsmirror.net/stats][up]]

* Introduction

This page contains statistics about the licenses used by known Emacs
packages.  *These statistics are not legal advice.  They are
distributed in the hope that they will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.*

The information used here is available from the Emacsmirror database
(also known as the Epkg database).  For more information about the
Emacsmirror see these [[https://emacsair.me/2016/04/16/re-introducing-the-emacsmirror][blog]] [[https://emacsair.me/2016/05/17/assimilate-emacs-packages-as-git-submodules][posts]].

I have created this page to accompany [[http://lists.gnu.org/archive/html/emacs-devel/2017-07/msg00341.html][this]] conversation on
~emacs-devel~.

I will periodically update the these statistics.  If you want to do so
yourself, then read the relevant documentation.  You may also ask me
for guidance.

This information is extracted using the function ~elx-license~, which is
provided by my package [[https://github.com/tarsius/elx][elx]] (~git clone https://github.com/tarsius/elx.git~).

The license is determined from the contents of the "main library" of
the package alone (the library whose name matches the name of the
package).  First this function looks for a permission statement for a
license published by the Free Software Foundation, if any.  If that
fails, then the value of the "License" header keyword is considered.
Finally it searches for brief, and potentially ambiguous, permission
statements for non-FSF licenses.  For FSF licenses a "+" is appended
if the text "or (at your option) any later version", or similar was
found.  An effort is made to normalize the returned value.  This
function also accounts for some commonly used variations in wording,
typos, and other complications.

However the returned value is sometimes false or ambiguous.  In
particular note that if a license is "unknown", then that merely means
that it is /not known/ what license applies.  This may be because the
library lacks a permission statement altogether (possibly because an
accompanying ~LICENSE~ file is considered sufficient by the upstream),
but it may also be because ~elx-license~ does not attempt to detect the
used non-standard and/or non-fsf permission statement, or because of
typos in the statement, or for a number of other reasons.

* Licenses used by packages on Melpa

https://melpa.org

#+NAME: count-melpa
#+BEGIN_SRC emacs-lisp
  (emir--format-license-table
   (epkg-sql [:select :distinct [packages:license (funcall count *)] :as count
              :from [packages melpa-recipes]
              :where (= packages:name melpa-recipes:epkg-package)
              :group-by packages:license
              :order-by count :desc]))
#+END_SRC
#+RESULTS: count-melpa
| License       | Count | Percent |
|---------------+-------+---------|
| GPL-3+        |  2230 |      61 |
| GPL-2+        |   611 |      17 |
| (unknown)     |   511 |      14 |
| as-is         |    91 |       2 |
| MIT           |    70 |       2 |
| public-domain |    52 |       1 |
| GPL-3         |    41 |       1 |
| GPL-2         |    31 |       1 |
| Apache-2.0    |    18 |       0 |
| GPL-1+        |     4 |       0 |
| BSD           |     3 |       0 |
| GPL           |     2 |       0 |
| LGPL          |     2 |       0 |
| AGPL-3        |     1 |       0 |
| AGPL-3+       |     1 |       0 |
| BSD-3         |     1 |       0 |
| EPL           |     1 |       0 |
| LGPL-3+       |     1 |       0 |
| LGPL-3.0      |     1 |       0 |
|---------------+-------+---------|
| total GNU     |  2925 |      80 |
|---------------+-------+---------|
| total         |  3672 |     100 |

* Licenses used by packages on the Emacsmirror

The Emacsmirror is a growing collection of Emacs Lisp packages. All
mirrored packages are available as Git repositories. In most cases
this is done by mirroring the upstream Git repository, but if upstream
uses something else, then the mirror nevertheless makes the package
available as a Git repository.

https://emacsmirror.net

#+NAME: count-emacsmirror
#+BEGIN_SRC emacs-lisp
  (emir--format-license-table
   (epkg-sql [:select [license (funcall count *)] :as count
              :from packages
              :where (and (not (= class 'builtin))
                          (not (= class 'elpa))
                          (not (= class 'elpa-branch))
                          (not (= class 'shelved)))
              :group-by license
              :order-by count :desc]))
#+END_SRC
#+RESULTS: count-emacsmirror
| License       | Count | Percent |
|---------------+-------+---------|
| GPL-3+        |  2684 |      53 |
| GPL-2+        |  1341 |      26 |
| (unknown)     |   648 |      13 |
| as-is         |    92 |       2 |
| GPL-2         |    74 |       1 |
| MIT           |    74 |       1 |
| public-domain |    67 |       1 |
| GPL-3         |    41 |       1 |
| Apache-2.0    |    18 |       0 |
| GPL-1+        |    13 |       0 |
| GPL           |     5 |       0 |
| BSD           |     3 |       0 |
| LGPL-3+       |     2 |       0 |
| AGPL-3        |     1 |       0 |
| AGPL-3+       |     1 |       0 |
| BSD-3         |     1 |       0 |
| EPL           |     1 |       0 |
| LGPL          |     1 |       0 |
| LGPL-3.0      |     1 |       0 |
|---------------+-------+---------|
| total GNU     |  4164 |      82 |
|---------------+-------+---------|
| total         |  5068 |     100 |

* Licenses uses by packages on the Emacsattic

Once its upstream has disappeared a package is usually moved from the
Emacsmirror to the Emacsattic, where it is no longer updated. (The
Emacsattic is a Github “organization” separate from the Emacsmirror
organization, but it is considered part of the Emacsmirror project.)

https://emacsmirror.net

#+NAME: count-emacsattic
#+BEGIN_SRC emacs-lisp
  (emir--format-license-table
   (epkg-sql [:select [license (funcall count *)] :as count
              :from packages
              :where (= class 'shelved)
              :group-by license
              :order-by count :desc]))
#+END_SRC
#+RESULTS: count-emacsattic
| License       | Count | Percent |
|---------------+-------+---------|
| GPL-2         |   509 |      52 |
| (unknown)     |   296 |      30 |
| GPL-3         |   141 |      14 |
| GPL           |    16 |       2 |
| GPL-1         |     9 |       1 |
| as-is         |     6 |       1 |
| Apache-2.0    |     3 |       0 |
| public-domain |     2 |       0 |
| MIT           |     1 |       0 |
|---------------+-------+---------|
| total GNU     |   675 |      69 |
|---------------+-------+---------|
| total         |   983 |     100 |

* Licenses uses by all known packages

This includes built-in, Elpa, and those from the Emacsattic.  Or in
other words, this includes each and every packages that has an entry
in the Emacsmirror database.

An overview of those packages, the version control systems used by
their upstreams, and the availability in other "package archives",
can be found [[https://emacsmirror.net/stats/compare.html][here]].

#+NAME: count-all
#+BEGIN_SRC emacs-lisp
  (emir--format-license-table
   (epkg-sql [:select [license (funcall count *)] :as count
              :from packages
              :group-by license
              :order-by count :desc]))
#+END_SRC
#+RESULTS: count-all
| License       | Count | Percent |
|---------------+-------+---------|
| GPL-3+        |  2782 |      42 |
| GPL-2+        |  1344 |      20 |
| (unknown)     |   948 |      14 |
| GPL-3         |   600 |       9 |
| GPL-2         |   583 |       9 |
| as-is         |    98 |       1 |
| MIT           |    75 |       1 |
| public-domain |    74 |       1 |
| Apache-2.0    |    21 |       0 |
| GPL           |    21 |       0 |
| GPL-1+        |    13 |       0 |
| GPL-1         |     9 |       0 |
| BSD           |     3 |       0 |
| LGPL-3+       |     2 |       0 |
| AGPL-3        |     1 |       0 |
| AGPL-3+       |     1 |       0 |
| BSD-3         |     1 |       0 |
| EPL           |     1 |       0 |
| LGPL          |     1 |       0 |
| LGPL-3.0      |     1 |       0 |
|---------------+-------+---------|
| total GNU     |  5358 |      81 |
|---------------+-------+---------|
| total         |  6579 |     100 |


