#+SETUPFILE: .orgconfig
#+NAME: setup
#+BEGIN_SRC emacs-lisp :results silent
  (require 'epkg)

  (defun emir--format-license-table (table)
    (--when-let (assq nil table)
      (setcar it "((unknown))"))
    (--when-let (assoc "pending" table)
      (setcar it  "((pending))"))
    (--when-let (assoc "failure" table)
      (setcar it  "((failure))"))
    (--when-let (assoc "failure(p)" table)
      (setcar it  "((failure/p))"))
    (--when-let (assoc "none" table)
      (setcar it  "((none))"))
    (let ((total (apply '+ (mapcar 'cadr table)))
          (gnu   (apply '+ (mapcar (pcase-lambda (`(,license ,count))
                                     (if (string-match-p "GPL" license) count 0))
                                   table))))
        (cl-flet ((percent (n) (round (* (/ n total 1.0) 100))))
          `(("License" "Count" "Percent")
            hline ,@(mapcar (pcase-lambda (`(,license ,count))
                              (list license count (percent count)))
                            table)
            hline ("total GNU" ,gnu ,(percent gnu))
            hline ("total" ,total 100)))))
#+END_SRC
[[https://emacsmirror.net/stats][up]]

* Introduction

This page contains statistics about the licenses used by known Emacs
packages.  *These statistics are not legal advice.  They are
distributed in the hope that they will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.*

The information used here is available from the Emacsmirror database
(also known as the Epkg database).  For more information about the
Emacsmirror see these [[https://emacsair.me/2016/04/16/re-introducing-the-emacsmirror][blog]] [[https://emacsair.me/2016/05/17/assimilate-emacs-packages-as-git-submodules][posts]].

I have created this page to accompany [[http://lists.gnu.org/archive/html/emacs-devel/2017-07/msg00341.html][this]] conversation on
~emacs-devel~.

I will periodically update the these statistics.  If you want to do so
yourself, then read the relevant documentation.  You may also ask me
for guidance.

This information is extracted using the function ~elx-license~, which is
provided by my package [[https://github.com/tarsius/elx][elx]].  This package is currently undergoing big
changes.

The extracted value is sometimes false or ambiguous.  In particular
note that if a license is "unknown", then that merely means that it is
/not known/ what license applies.  This may be because the library lacks
a permission statement and ~LICENSE~ file altogether, but it may also be
because ~elx-license~ does not attempt to detect the used non-standard
and/or non-fsf permission statement, or because of typos in the
statement, or for a number of other reasons.

* Licenses used by packages on Melpa

https://melpa.org

#+NAME: count-melpa
#+BEGIN_SRC emacs-lisp
  (emir--format-license-table
   (epkg-sql [:select :distinct [packages:license (funcall count *)] :as count
              :from [packages melpa-recipes]
              :where (= packages:name melpa-recipes:epkg-package)
              :group-by packages:license
              :order-by [(desc count) (asc license)]]))
#+END_SRC
#+RESULTS: count-melpa
| License       | Count | Percent |
|---------------+-------+---------|
| GPL-3+        |  2483 |      66 |
| GPL-2+        |   615 |      16 |
| MIT (x11)     |   128 |       3 |
| MIT           |   124 |       3 |
| GPL-3         |   121 |       3 |
| BSD-2-clause  |    68 |       2 |
| BSD-3-clause  |    35 |       1 |
| Apache-2.0    |    33 |       1 |
| unlicense     |    31 |       1 |
| public-domain |    26 |       1 |
| as-is         |    19 |       1 |
| ((failure))   |    14 |       0 |
| WTFPL         |    13 |       0 |
| ((failure/p)) |    13 |       0 |
| GPL-1+        |     4 |       0 |
| WTFPL-2       |     4 |       0 |
| AGPL-3+       |     3 |       0 |
| BEER-WARE     |     3 |       0 |
| ISC (and)     |     3 |       0 |
| ISC (and/or)  |     3 |       0 |
| LGPL-3+       |     3 |       0 |
| Artistic-2.0  |     2 |       0 |
| CeCILL-B      |     2 |       0 |
| GPL-2         |     2 |       0 |
| LGPL          |     2 |       0 |
| MS-PL         |     2 |       0 |
| BSD           |     1 |       0 |
| COPYLOVE      |     1 |       0 |
| LGPL-2.1      |     1 |       0 |
| LGPL-3        |     1 |       0 |
| LGPL-3.0      |     1 |       0 |
| MPL-2         |     1 |       0 |
| zlib License  |     1 |       0 |
|---------------+-------+---------|
| total GNU     |  3236 |      86 |
|---------------+-------+---------|
| total         |  3763 |     100 |

* Licenses used by packages on the Emacsmirror

The Emacsmirror is a growing collection of Emacs Lisp packages. All
mirrored packages are available as Git repositories. In most cases
this is done by mirroring the upstream Git repository, but if upstream
uses something else, then the mirror nevertheless makes the package
available as a Git repository.

https://emacsmirror.net

#+NAME: count-emacsmirror
#+BEGIN_SRC emacs-lisp
  (emir--format-license-table
   (epkg-sql [:select [license (funcall count *)] :as count
              :from packages
              :where (and (not (= class 'builtin))
                          (not (= class 'elpa))
                          (not (= class 'elpa-branch))
                          (not (= class 'shelved)))
              :group-by license
              :order-by [(desc count) (asc license)]]))
#+END_SRC
#+RESULTS: count-emacsmirror
| License         | Count | Percent |
|-----------------+-------+---------|
| GPL-3+          |  2957 |      58 |
| GPL-2+          |  1339 |      26 |
| MIT (x11)       |   127 |       3 |
| MIT             |   127 |       3 |
| GPL-3           |   126 |       2 |
| BSD-2-clause    |    71 |       1 |
| public-domain   |    48 |       1 |
| BSD-3-clause    |    38 |       1 |
| unlicense       |    33 |       1 |
| WTFPL           |    32 |       1 |
| Apache-2.0      |    31 |       1 |
| as-is           |    23 |       0 |
| ((failure))     |    23 |       0 |
| ((failure/p))   |    15 |       0 |
| ((pending))     |    13 |       0 |
| GPL-2           |     7 |       0 |
| GPL-1+          |     6 |       0 |
| WTFPL-2         |     5 |       0 |
| LGPL-3+         |     4 |       0 |
| AGPL-3+         |     3 |       0 |
| ISC (and)       |     3 |       0 |
| ISC (and/or)    |     3 |       0 |
| MS-PL           |     3 |       0 |
| Artistic-2.0    |     2 |       0 |
| COPYLOVE        |     2 |       0 |
| CeCILL-B        |     2 |       0 |
| BEER-WARE       |     1 |       0 |
| BSD             |     1 |       0 |
| CC BY-NC-SA 3.0 |     1 |       0 |
| CC BY-SA 4.0    |     1 |       0 |
| GPL             |     1 |       0 |
| GPL-3.0         |     1 |       0 |
| LGPL            |     1 |       0 |
| LGPL-2.1        |     1 |       0 |
| LGPL-3          |     1 |       0 |
| LGPL-3.0        |     1 |       0 |
| MPL-2           |     1 |       0 |
| zlib License    |     1 |       0 |
|-----------------+-------+---------|
| total GNU       |  4448 |      88 |
|-----------------+-------+---------|
| total           |  5055 |     100 |
