name: Publish
permissions: {}
on:
  workflow_dispatch:
  push:
    branches: main
jobs:
  publish:
    name: Publish
    uses: | # zizmor: ignore[unpinned-uses] same maintainer as this repo
      emacscollective/workflows/.github/workflows/publish.yml@main
    secrets:
      rclone_config: ${{ secrets.RCLONE_CONFIG }}
